### ISSUE TITLE
Translating User Interface

### ISSUE THREAD

**Issue by SeanCompier** [luontola/territory-bro#13]
Is it possible to translate the website, so those assigned to it can understand using it? 

I can help by translating into Dutch.

Kind Regards,

Your brother,

Sean Compier

**Comment by luontola** [comment]
The application has now been machine-translated to all previously supported languages, including Dutch. Please go through the [Dutch translation](https://github.com/luontola/territory-bro/blob/master/web/src/locales/nl/translation.yaml), compare them with the [English translation](https://github.com/luontola/territory-bro/blob/master/web/src/locales/en/translation.yaml) and report if there are things that could be improved.

**Comment by SeanCompier** [comment]
Dear Brother,

Thank you very much for your work. I no longer serve in the congregation
that used Territory Bro, but I am sure they will appreciate it.

Regards,

Seán Compier
